"""Update Assessments schema

Revision ID: 8157157aa59f
Revises: 8120031fa828
Create Date: 2024-09-04 17:25:11.179750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8157157aa59f'
down_revision = '8120031fa828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date_taken', sa.DateTime(), nullable=False))
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('date_taken')
        batch_op.drop_column('score')
        batch_op.drop_column('grade_level')

    # ### end Alembic commands ###
